Update test-cases.md
sofisanabria/DigitalBank-Test pull request #5
Opened 2022-03-16 17:16 UTC by sofisanabria

2022-03-16 18:54 UTC, roxanafalco20 approved these changes
Green light on my end :)

2022-03-18 17:30 UTC, santiago-abstracta requested changes

2022-03-18 17:30 UTC, santiago-abstracta commented on Test-DigitalBank/test/depositflow.test.js
> +        await expect(AccountView.balanceText).toHaveTextContaining(expectedBalance)
You can also verify if the deposit was actually made by checking the corresponding table.

2022-03-22 13:25 UTC, santiago-abstracta commented on Test-DigitalBank/data/depositflowtest.js
> +module.exports = [
Done.

2022-03-22 13:25 UTC, santiago-abstracta commented on Test-DigitalBank/data/depositflowtest.js
> +    {index: 2, amount: "1000"}
Done.

2022-03-22 13:28 UTC, santiago-abstracta commented on Test-DigitalBank/pages/deposit.page.js
>      async findDepositMessage(){
Done.

2022-03-22 13:28 UTC, santiago-abstracta commented on Test-DigitalBank/pages/deposit.page.js
> +    async getBalanceAmount(){
We still need to have that conversation!

2022-03-22 13:31 UTC, santiago-abstracta commented on Test-DigitalBank/pages/deposit.page.js
> +    async getBalanceAmount(){
Done.

2022-03-22 13:33 UTC, santiago-abstracta commented on Test-DigitalBank/pages/home.page.js
>    get withdrawPageMenuItem(){
Done.

2022-03-22 13:33 UTC, santiago-abstracta commented on Test-DigitalBank/pages/home.page.js
> +  get depositPage(){
Done.

2022-03-22 13:36 UTC, santiago-abstracta commented on Test-DigitalBank/pages/home.page.js
>    async backtologinpage() {
I understand now! I believe this method should be called `logOut()`.

2022-03-22 14:28 UTC, santiago-abstracta commented on Test-DigitalBank/wdio.conf.js
> +import {addStep} from '@wdio/allure-reporter'
Good! It'd be great to see steps in your tests :)

2022-03-22 14:28 UTC, santiago-abstracta commented on Test-DigitalBank/test/withdraw.test.js
>          await browser.url(' ');
You can call the `logOut()` method from any page as it depends on an element that's always present, so this line isn't necessary.

2022-03-22 14:28 UTC, santiago-abstracta commented on Test-DigitalBank/test/login.test.js
>      await expect(welcometext).toEqual("Welcome Josh");
This also works: `await expect(await HomePage.getWelcomeText()).toEqual("Welcome Josh")`.

2022-03-22 14:28 UTC, santiago-abstracta commented on Test-DigitalBank/test/depositflow.test.js
> +    await LoginPage.clickLogInButton();
Done.

2022-03-22 14:29 UTC, santiago-abstracta commented on Test-DigitalBank/test/depositflow.test.js
> +  beforeEach(async () => {
Thanks for reaching out to me!

2022-03-22 17:37 UTC, santiago-abstracta requested changes

2022-03-22 17:37 UTC, santiago-abstracta commented on Test-DigitalBank/views/account.view.js
> +    }
What happens if there's more than one card in the account view?

2022-03-22 17:37 UTC, santiago-abstracta commented on Test-DigitalBank/test/depositflow.test.js
> +        await expect(AccountView.balanceText).toHaveTextContaining(expectedBalance)
I believe it's better to check if the first row corresponds to the last deposit made.

2022-03-22 17:37 UTC, santiago-abstracta commented on Test-DigitalBank/test/depositflow.test.js
> +        await DepositPage.clickSubmitButton();
Clicking this button should be part of the `deposit()` method.

2022-03-22 17:37 UTC, santiago-abstracta commented on Test-DigitalBank/test/deposit.test.js
> +        await HomePage.backToLoginPage();
`logOut()`

2022-03-22 17:37 UTC, santiago-abstracta commented on Test-DigitalBank/pages/login.page.js
> +    await this.fillLogInForm("jsmith@demo.io", "Demo123!");
Let's talk about this through Google Meet.

2022-03-22 17:41 UTC, santiago-abstracta commented on Test-DigitalBank/test/deposit.test.js
>          await LoginPage.clickLogInButton();
Done.

2022-03-22 17:42 UTC, santiago-abstracta commented on Test-DigitalBank/test/depositflow.test.js
> +  beforeEach(async () => {
Done.

2022-03-22 17:42 UTC, santiago-abstracta commented on Test-DigitalBank/test/depositflow.test.js
> +  dataDepositFlow.forEach((depositData) => {
Done.

2022-03-22 17:44 UTC, santiago-abstracta requested changes

2022-03-22 17:44 UTC, santiago-abstracta commented on Test-DigitalBank/test/withdraw.test.js
>      it('Sould show the withdraws page', async () => {
should*

2022-03-22 17:44 UTC, santiago-abstracta commented on Test-DigitalBank/test/depositflow.test.js
> +    it(`Create a deposit with amount ${depositData.amount}`, async () => {
Done.

2022-03-22 17:44 UTC, santiago-abstracta commented on Test-DigitalBank/test/depositflow.test.js
> +        await DepositPage.fillAmount(depositData.amount);
Done.

2022-03-23 22:20 UTC, santiago-abstracta commented on Test-DigitalBank/test/depositflow.test.js
> +      addStep("Create Deposit")
I'd like to see more steps in the next Nano!

2022-03-23 22:24 UTC, santiago-abstracta approved these changes

2022-03-24 12:09 UTC, merged